module.exports = function(Huebot)
{
  Huebot.commands = 
  [
    {name:"image", description:"", public:false},
    {name:"tv", description:"", public:false},
    {name:"radio", description:"", public:false},
    {name:"set", description:"", public:false},
    {name:"setforce", description:"", public:false},
    {name:"unset", description:"", public:false},
    {name:"rename", description:"", public:false},
    {name:"list", description:"", public:true},
    {name:"random", description:"", public:true},
    {name:"q", description:"", public:true},
    {name:"adminadd", description:"", public:false},
    {name:"adminremove", description:"", public:false},
    {name:"admins", description:"", public:false},
    {name:"themeadd", description:"", public:false},
    {name:"themeremove", description:"", public:false},
    {name:"themerename", description:"", public:false},
    {name:"theme", description:"", public:false},
    {name:"themes", description:"", public:false},
    {name:"linktitles", description:"", public:false},
    {name:"stream", description:"", public:false},
    {name:"activity", description:"", public:false},
    {name:"clearcommands", description:"", public:false},
    {name:"clearadmins", description:"", public:false},
    {name:"clearthemes", description:"", public:false},
    {name:"clearsubjects", description:"", public:false},
    {name:"help", description:"", public:false},
    {name:"ping", description:"", public:false},
    {name:"whatis", description:"", public:false},
    {name:"say", description:"", public:false},
    {name:"subjectadd", description:"", public:false},
    {name:"subjectremove", description:"", public:false},
    {name:"subjectrename", description:"", public:false},
    {name:"subjectkeywords", description:"", public:false},
    {name:"subjectkeywordsadd", description:"", public:false},
    {name:"subjectkeywordsremove", description:"", public:false},
    {name:"subject", description:"", public:true},
    {name:"subjects", description:"", public:false},
    {name:"leave", description:"", public:false},
    {name:"join", description:"", public:false},
    {name:"backgroundadd", description:"", public:false},
    {name:"backgroundremove", description:"", public:false},
    {name:"backgroundrename", description:"", public:false},
    {name:"background", description:"", public:false},
    {name:"backgrounds", description:"", public:false},
    {name:"backgroundmode", description:"", public:false},
    {name:"clearbackgrounds", description:"", public:false},
    {name:"thememode", description:"", public:false},
    {name:"sleep", description:"", public:false},
    {name:"suggest", description:"", public:false},
    {name:"song", description:"", public:false},
    {name:"key", description:"", public:false},
    {name:"speak", description:"", public:false},
    {name:"think", description:"", public:false},
    {name:"think2", description:"", public:false},
    {name:"public", description:"", public:false},
    {name:"remind", description:"", public:false},
    {name:"calc", description:"", public:true},
    {name:"roll", description:"", public:true},
    {name:"users", description:"", public:true},
    {name:"decide", description:"", public:true},
    {name:"pick", description:"", public:true},
    {name:"wiki", description:"", public:true},
  ]

  Huebot.command_list = []

  for(let key in Huebot.commands) {
    Huebot.command_list.push(Huebot.commands[key].name)
  }
}